services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - .:/var/www
    networks:
      - app-network

  # MySQL Service
  db:
    image: mariadb:10.4
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: maikelca_inventary
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "8085:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
