name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4


      - name: 🛠️ Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: 📦 Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install JS dependencies
        run: npm install

      - name: 🚀 Build assets
        run: npm run build

      - name: 🔑 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          known_hosts: unnecessary # Lo manejaremos en el siguiente paso
          if_key_exists: fail

      - name: 🛡️ Adding Known Hosts
        run: ssh-keyscan -p 22 ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts

      - name: 🚀 Deploy with rsync
        run: |
          rsync -avz -e "ssh -p 22 -o IdentitiesOnly=yes" \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='tests' \
            --exclude='.env*' \
            --exclude='*.pdf' \
            --exclude='phpunit.xml' \
            --exclude='vite.config.js' \
            --exclude='tailwind.config.js' \
            --exclude='postcss.config.js' \
            --exclude='composer.*' \
            --exclude='package*' \
            . ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/home/maikelca/internal.maikelcars.com/
